### ISSUE TITLE
Details page in addons manager links to nonexistent AMO addon page

### ISSUE THREAD

**Issue by tonymec** [lemon-juice/AMO-Browsing-for-SeaMonkey#1]
In the details page for this addon (version 0.9.0), the "Homepage" item links to https://addons.mozilla.org/addon/amo-browsing/ which is undefined (I get a custom site-specific 404 error page, "We're sorry, but we can't find what you're looking for.")

**Comment by lemon-juice** [comment]
Fixed in 0.9.2.

**Comment by tonymec** [comment]
The link is now to https://github.com/lemon-juice/AMO-Browsing-for-SeaMonkey

If this were Bugzilla I would set the status of the bug to VERIFIED. :-)
