### ISSUE TITLE
Stopped working at AMO

### ISSUE THREAD

**Issue by graciecat** [lemon-juice/AMO-Browsing-for-SeaMonkey#10]
This extension was working fine after I installed it, until quite recently. Now it doesn't seem to work. I do not get the button "Check if SeaMonkey version is available" or the link "Convert this add-on here".

**Comment by RainerBielefeld** [comment]
I additionally submitted "Bug 1389022 - "AMO Browsing for SeaMonkey" does not work any longer" <https://bugzilla.mozilla.org/show_bug.cgi?id=1389022> so that the problem also becomes known for additional users and developers.
I left a comment in the Add-On descriptions (German, English) on AMO.

**Comment by grahamperrin** [comment]
From [Unify categories · Issue mozilla/addons#4579 · mozilla/addons-server](https://github.com/mozilla/addons/issues/4579): 

> … SeaMonkey: we plan to move to a separate site. …

**Comment by dogbows** [comment]
I'm lost.  Is there a fix for this bug?

**Comment by RainerBielefeld** [comment]
I wonder whether lemon-juice still is active here.
@IsaacSchemm: Can you provide a version of the add-on with your fixes somewhere else? Some times ago I created https://sourceforge.net/projects/seamonkeyaddons/ for such tests, we can use that if you don't have a better idea.

**Comment by IsaacSchemm** [comment]
I'd like to wait for at least a week. But if I never hear from Lemon Juice, I suppose I could fork the extension and upload my own version there or to AMO. As far as I know, AMO still accepts legacy extensions as long as they don't target Firefox.

(The devs would want to update the SeaMonkey help page to point to the new extension, in that case.)

**Comment by RainerBielefeld** [comment]
@IsaacSchemm 
1. We should have a test version ASAP which can be downloaded from here or your github area or somewhere else so that some users can try your fixes. Can you send an .xpi to me?
2. If test results are promising we should upload a new version to AMO. My role for "AMO Browsing for SeaMonkey" is "developer", so I think I can not give you a "developer" role for that add-on.

**Comment by IsaacSchemm** [comment]
@RainerBielefeld 

Here you go. I think I've done everything I wanted to do.
https://github.com/IsaacSchemm/AMO-Browsing-for-SeaMonkey/releases/tag/v0.9.16a1

**Comment by IsaacSchemm** [comment]
@RainerBielefeld 
Have you had a chance to try it out yet?

**Comment by RainerBielefeld** [comment]
I will do some systematic tests today in the evening.
Do you have an Idea concerning distribution of the new version? After some tests, if you think it's ready, I can upload it as a new Version to AMO. Additionally I can try to get a developer or owner role for you, because I would prefer to leave it at it's old place to offer download from a new place.

**Comment by IsaacSchemm** [comment]
I would like it to be an update to the existing extension, since it's already linked in SeaMonkey Help.
Whether or not you want to give me a developer or owner role, that is up to you :)

**Comment by RainerBielefeld** [comment]
I already did some tests, looks promising, detailed results tomorrow!

**Comment by lemon-juice** [comment]
Hi guys! Sorry for being silent so long but I've been too busy recently to be able to take care of this project. I was also sceptical if it makes sense to work with a moving target like AMO, which can change at any time soon. But anyway, as long as anyone wants to contribute then it's great!

Isaac, perhaps you want to become the collaborator of this project? This way you will be able to manage it and upload any changes here - I think it's easier for users if a project is not fragmented into forks. I can also give you access to the AMO listing, too - just send me your email address.

**Comment by IsaacSchemm** [comment]
@lemon-juice Thanks! My email is isaacschemm@gmail.com (it's also in all my git commits so not exactly a secret.)

**Comment by lemon-juice** [comment]
I've given you access to both so let me know if you have any problems.

**Comment by IsaacSchemm** [comment]
@RainerBielefeld I'll wait for your feedback (at least a day or two) before uploading the new version.

I also saw that AMO has an API now :)

**Comment by RainerBielefeld** [comment]
Fixes work great, [here](http://wp.me/p7kLBG-dp) my test results

**Comment by IsaacSchemm** [comment]
Thanks for checking!

Do you think I should change the creator in install.rdf to myself and make Lemon Juice contributor, or vice versa?

EDIT: I think I'll put both our names in the creator field. It doesn't look like this gets used anyway (unless an add-on is not on AMO.)

**Comment by RainerBielefeld** [comment]
I don't have experience with these formal queststions.

**Comment by RainerBielefeld** [comment]
I think we should close this one, which is related to add-on version 0.9.16.
