### ISSUE TITLE
Version 0.9.17b1 does not work for me on new AMO

### ISSUE THREAD

**Issue by RainerBielefeld** [lemon-juice/AMO-Browsing-for-SeaMonkey#12]
Isaacs [Screenshot](https://i.imgur.com/1oyDqU3.png) looks fine, but for me 0.9.17b1 only works on AMO, not on addons-dev.allizom.org with new AMO design.

**Examples I where my tests failed
![addons-dev_allizom_org_en-us_seamonkey_addon_flashblock](https://user-images.githubusercontent.com/11803749/32210443-eae3561c-be0d-11e7-9d3b-c6ddea3fdb87.png)
**:
Screenshot from [Flashblock](https://addons-dev.allizom.org/en-US/seamonkey/addon/flashblock/) 

[uBlock Origin/webext von CosminSV](https://addons-dev.allizom.org/de/firefox/addon/ublock-origin-webext/), [BlockSite von Wips.com s.r.o](https://addons-dev.allizom.org/de/firefox/addon/blocksite/)., LEOs [Dictionaries von LEO GmbH](https://addons-dev.allizom.org/de/firefox/addon/leos-dictionaries/), any other tested on  [addons-dev.allizom.org](https://addons-dev.allizom.org/de/firefox/addon/)

a) I did my tests with unzipped installer of  official en-US SeaMonkey 2.53a1 (NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0 Build 20170706013410  (Default Classic Theme) on German WIN7 64bit + AMO-Browsing-for-SeaMonkey  0.9.17b1 here from Github

a1) also does not work with 2.49.1 and a seldom used test profile.

b) also does not work on [https://addons-dev.allizom.org/en-US/firefox/addon/leos-dictionaries/](https://addons-dev.allizom.org/en-US/firefox/addon/leos-dictionaries/)  and other en-US pages

c) @Isaac: please tell how you did your successful test.

**Comment by IsaacSchemm** [comment]
I used the normal site at https://addons.mozilla.org/. If you scroll down to the bottom of the page and click "View Mobile Site" (or "Zur mobilen Version"), it will add a cookie "mamo=on" which takes you to the new version of the site. I got this from the blog post: https://blog.mozilla.org/addons/2017/10/25/test-new-look-addons-mozilla-org/

I didn't see the link to addons-dev.allizom.org in that blog post, so I forgot to add support for that site.

Later today I'll post a new beta version (0.9.17b2) that works on both addons.mozilla.org and addons-dev.allizom.org, among other changes.

**Comment by IsaacSchemm** [comment]
I posted the new beta version:
https://github.com/lemon-juice/AMO-Browsing-for-SeaMonkey/releases/tag/v0.9.17b2

**Comment by RainerBielefeld** [comment]
The problems I saw first might be related to a problem with the different domain of the developers test  area.

But also in the "mobile view" I see problems - the new problems might be caused by interaction with active addons, other preferences, ... . More investigation required.

d1) view with test profile, very few preferences changed, very few add-ons:
![soitlookswithmytestprofile](https://user-images.githubusercontent.com/11803749/32231929-2725085c-be57-11e7-8993-6b5b698214cd.png)

d2) view with my normal profile
![soitlookswithmynormalprofile](https://user-images.githubusercontent.com/11803749/32231940-30145706-be57-11e7-9063-3d8b291d818d.png)

**Comment by IsaacSchemm** [comment]
Could you try again with the new beta version when you have time? Let me know if you see any problems with that one.

**Comment by RainerBielefeld** [comment]
Well, my remaining problem has nothing to do with active add-ons.

Now I will test b2

**Comment by RainerBielefeld** [comment]
B2 automatically leads to The newest uBlock Origin SeaMonkey-compatible version 1.13.8, released on July 18, 2017. Great improvement. Do you already prepare a "New Features" list for .17?
The red "Download FF" bar still is on "BlockSite" download page, I will try to find the reason later, so that you can decide whether this problem is of general interest.

**Comment by IsaacSchemm** [comment]
I don't have a "new features" list yet, but I can create one.

I haven't tried to get rid of the red button yet, but that's a good idea. I always leave "Advertise Firefox compatiblity" on, and I think that's why it never showed up for me.

**Comment by IsaacSchemm** [comment]
@RainerBielefeld Do you have a preference between these 2 options?
https://imgur.com/a/WOdnW

**Comment by RainerBielefeld** [comment]
I prefer the upper design, because it shows SeaMonkey related information in a separate gray area, what IMHO helps to distinguish this from general add-on information.

**Comment by IsaacSchemm** [comment]
I uploaded 0.9.17rc1. Would you mind checking to see if everything works for you? If so, I'll upload it to AMO as the new version.

**Comment by RainerBielefeld** [comment]
The reason for original report was some misunderstanding, 0.9.16 simply did not support dev. area on AMO. I have not yet tested 0.9.17 there.

In AMO I did some tests with  0.9.17, all [successful](https://wp.me/p7kLBG-dI). I If nobody else has concerns, Isaac should upload new version 0.9.17 to AMO. As soon as it will have passed AMO review process, I will adapt screenshots and so on.
