### ISSUE TITLE
Version 0.9.16.1 does not work at AMO (SeaMonkey 2.48 on Ubuntu 14.04)

### ISSUE THREAD

**Issue by graciecat** [lemon-juice/AMO-Browsing-for-SeaMonkey#13]
I recently upgraded to version 0.9.16.1 of your extension. I went to AMO, and I noticed … nothing. It does not work any better than version 0.9.15. I do not see the links "Check if SeaMonkey version is available" or "Convert this add-on here". The page looks the same with or without the extension enabled.

SeaMonkey 2.48
Ubuntu 14.04

UPDATE: After testing, I discovered an extension conflict. A filter I was using with [Modify HTTP Response](https://addons.mozilla.org/en-US/seamonkey/addon/modify-http-response/?src=search) was overriding AMO-Browsing-for-Seamonkey's javascript mods. It was so long in getting an update to your extension that I had added this filter to restore some functionality to AMO. Sorry for the confusion.

I disable the other extension, and now it works great! Thanks for making such an excellent and essential add-on!

**Comment by RainerBielefeld** [comment]
@graciecat; Thank you for testing. I observed similar problems with my standard profile, I will check whether my problem has the same roots like you.
