### ISSUE TITLE
AMO-Browsing-for-SeaMonkey should not recommend to install or try to adapt version number for Language packs

### ISSUE THREAD

**Issue by RainerBielefeld** [lemon-juice/AMO-Browsing-for-SeaMonkey#14]
Details see [here](https://wp.me/p7kLBG-e5) (Pay attention ...) and in "Bug [1386527](https://bugzilla.mozilla.org/show_bug.cgi?id=1386527) - Drop German Language Pack from AMO dictionaries page"

**Comment by IsaacSchemm** [comment]
Looks like I can detect whether something is a language pack from the API (type: "language") :)

**Comment by IsaacSchemm** [comment]
I just posted 0.9.17.1 rc1 which should fix this. Could you try it?

**Comment by RainerBielefeld** [comment]
Yes, results day after tomorrow!
