### ISSUE TITLE
Applicability, addons.thunderbird.net

### ISSUE THREAD

**Issue by grahamperrin** [lemon-juice/AMO-Browsing-for-SeaMonkey#18]
Hi 

Since SeaMonkey now uses `addons.thunderbird.net`, is it OK to continue using this extension; is the extension known to cause any issue/problem with the service? 

At e.g. https://addons.thunderbird.net/en-GB/seamonkey/addon/amo-browsing-for-seamonkey/?src=search I see the **View version history** button that is a feature of the extension; I'm not sure what else is done.

**Comment by IsaacSchemm** [comment]
This extension is designed to work with addons.thunderbird.net (as well as addons.mozilla.org), and I don't know of any problems that it would cause.

The other big feature it adds is a custom search page, which you can reach from the link in the upper-right corner ("Or use the AMO Browsing extension to search").

**Comment by grahamperrin** [comment]
OK, that's cool! Thanks. 

chrome://amobrowsing/content/search.html?q=theme&host=addons.thunderbird.net&type=extension&sort=created&app=seamonkey

… and so on. I'll close this. 

----

Off-topic from SeaMonkey, I wonder whether any of the code here might help with something for Waterfox users. Are you ever in `#seamonkey` on IRC?

**Comment by IsaacSchemm** [comment]
> Are you ever in `#seamonkey` on IRC?

Once in a while, I suppose.

I suppose this could be somewhat useful for Waterfox, at least for browsing addons.mozilla.org and addons.thunderbird.net - the links to the SeaMonkey Add-on Converter won't do much good.
