### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by RainerBielefeld** [lemon-juice/AMO-Browsing-for-SeaMonkey#2]
I can't find any license terms in the source? I would have uploaded the extension to AMO due to https://wiki.mozilla.org/SeaMonkey/StatusMeetings/2016-02-02#Rainer_Bielefeld, but without Open Source License I will not do that.

**Comment by RainerBielefeld** [comment]
Problem solved with https://bugzilla.mozilla.org/show_bug.cgi?id=1230722#c6

**Comment by RainerBielefeld** [comment]
More or less fixed with License info in [AMO](https://addons.mozilla.org/de/seamonkey/addon/amo-browsing-for-seamonkey/)

**Comment by RainerBielefeld** [comment]
@Isaac, lemon-juice: Can we close this one?

**Comment by IsaacSchemm** [comment]
Since the MPL was the license listed on the AMO page you linked to, I added it to the repository here.

I'm OK with closing this issue. @lemon-juice, feel free to reopen it if you have anything to add.
