### ISSUE TITLE
link-(background-)colors for new amo

### ISSUE THREAD

**Issue by dex2000** [lemon-juice/AMO-Browsing-for-SeaMonkey#3]
New AMO is blue, the links are ... blue

plz add colors (or background-colors) for links
    color: #fbfbfb;
looks good here in testing with firebug

**Comment by RainerBielefeld** [comment]
Please close RfE "Bug 1263375 - AMO Browsing for SeaMonkey: Hyperlink to 
Converter needs more eye-catching color with new AMO Style" 
https://bugzilla.mozilla.org/show_bug.cgi?id=1263375 when resolved.

CU

Rainer

**Comment by lemon-juice** [comment]
fixed in 0.9.10
